"""Static GOVP-PUBLICATION-1 construction and verification."""

from __future__ import annotations

import base64
import hashlib
import json
import os
import re
import shutil
import ssl
import tempfile
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit
from urllib.request import HTTPRedirectHandler, HTTPSHandler, Request, build_opener

import certifi
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

from .core import load_record, verify
from .envelope import (
    canonical_json,
    load_envelope,
    sign_envelope,
    verify_envelope,
)
from .status import parse_status, status_format_ok

PUBLICATION_EXTENSION = {"id": "org.govp.publication", "version": "1.0.0"}
AUTHORIZATION_TYPE = "org.govp.subordinate-key/1"
BATCH_TYPE = "org.govp.publication-batch/1"
TREE_ALGORITHM = "sha256-rfc6962-sharded-256"
SHARDS = 256
EMPTY_ROOT = hashlib.sha256(b"").digest()
MAX_JSON_BYTES = 4 * 1024 * 1024
MAX_SUBJECT_BYTES = 64 * 1024 * 1024
TYPE_RE = re.compile(r"^[a-z0-9]+(?:\.[a-z0-9-]+)+/[1-9][0-9]*$")
KEY_ID_RE = re.compile(r"^sha256:[0-9a-f]{64}$")
SHA_RE = re.compile(r"^[0-9a-f]{64}$")
SAFE_ID_RE = re.compile(r"^[A-Za-z0-9._-]{1,128}$")


@dataclass(frozen=True)
class PublicationVerification:
    """Layered result for one publication inclusion bundle."""

    ok: bool
    layers: dict[str, bool | None]
    reasons: tuple[str, ...]
    event_id: str | None = None
    batch_id: str | None = None


@dataclass(frozen=True)
class PublicationOutput:
    """Locations and counts generated by a publication transaction."""

    public_dir: Path
    custody_dir: Path
    public_count: int
    sealed_count: int
    public_root: str | None
    sealed_root: str | None


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _key_id(raw_public_key: bytes) -> str:
    return f"sha256:{_sha(raw_public_key)}"


def _parse_json_bytes(raw: bytes, label: str) -> dict[str, Any]:
    if len(raw) > MAX_JSON_BYTES:
        raise ValueError(f"{label} exceeds the 4 MiB limit")
    try:
        text = raw.decode("utf-8", errors="strict")
    except UnicodeDecodeError as error:
        raise ValueError(f"{label} is not valid UTF-8") from error

    def reject_duplicates(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        value: dict[str, Any] = {}
        for key, item in pairs:
            if key in value:
                raise ValueError(f"{label} has duplicate object name: {key}")
            value[key] = item
        return value

    result = json.loads(text, object_pairs_hook=reject_duplicates)
    if not isinstance(result, dict):
        raise TypeError(f"{label} must be a JSON object")
    return result


def _load_json(path: Path, label: str) -> dict[str, Any]:
    return _parse_json_bytes(path.read_bytes(), label)


def _write_json(path: Path, value: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("x", encoding="utf-8", newline="\n") as handle:
        json.dump(value, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")


def _parse_time(value: Any, label: str) -> datetime:
    if not isinstance(value, str) or not value.endswith("Z"):
        raise ValueError(f"{label} must be an RFC 3339 UTC timestamp")
    try:
        result = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as error:
        raise ValueError(f"{label} must be an RFC 3339 UTC timestamp") from error
    if result.tzinfo is None or result.utcoffset() != timezone.utc.utcoffset(result):
        raise ValueError(f"{label} must be UTC")
    return result


def _domain(value: Any) -> str:
    if not isinstance(value, str) or len(value) > 2048:
        raise ValueError("domain must be an absolute HTTPS origin")
    parsed = urlsplit(value)
    if (
        parsed.scheme != "https"
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.path not in {"", "/"}
        or parsed.query
        or parsed.fragment
    ):
        raise ValueError("domain must be an absolute HTTPS origin")
    origin = f"https://{parsed.netloc}"
    if value.rstrip("/") != origin:
        raise ValueError("domain must use its canonical HTTPS origin spelling")
    return origin


def _safe_id(value: Any, label: str) -> str:
    if not isinstance(value, str) or not SAFE_ID_RE.fullmatch(value):
        raise ValueError(f"{label} is not a safe identifier")
    return value


def _resolve(root: Path, value: Any, label: str) -> Path:
    if not isinstance(value, str) or not value or len(value) > 512:
        raise ValueError(f"{label} must be a relative path")
    relative = Path(value)
    if relative.is_absolute() or ".." in relative.parts:
        raise ValueError(f"{label} must stay inside the request directory")
    candidate = (root / relative).resolve(strict=True)
    request_root = root.resolve(strict=True)
    if not candidate.is_relative_to(request_root) or not candidate.is_file():
        raise ValueError(f"{label} must stay inside the request directory")
    return candidate


def _load_private_key(path: Path) -> Ed25519PrivateKey:
    resolved = path.resolve(strict=True)
    if os.name != "nt" and resolved.stat().st_mode & 0o077:
        raise ValueError(
            f"private key permissions are too broad: {resolved} (use chmod 600)"
        )
    key = serialization.load_pem_private_key(resolved.read_bytes(), password=None)
    if not isinstance(key, Ed25519PrivateKey):
        raise TypeError("private key must be an Ed25519 PKCS8 PEM key")
    return key


def _load_public_key(path: Path) -> bytes:
    value = serialization.load_pem_public_key(path.resolve(strict=True).read_bytes())
    if not isinstance(value, Ed25519PublicKey):
        raise TypeError("subordinate public key must be Ed25519 PEM")
    return value.public_bytes(
        serialization.Encoding.Raw, serialization.PublicFormat.Raw
    )


def _public_raw(private_key: Ed25519PrivateKey) -> bytes:
    return private_key.public_key().public_bytes(
        serialization.Encoding.Raw, serialization.PublicFormat.Raw
    )


def _valid_type(value: Any) -> bool:
    return isinstance(value, str) and TYPE_RE.fullmatch(value) is not None


def _authorization_payload(payload: Any) -> dict[str, Any]:
    if not isinstance(payload, dict) or set(payload) != {
        "allowed_types",
        "domain",
        "key_id",
        "public_key",
        "valid_from",
        "valid_until",
    }:
        raise ValueError("authorization payload has missing or unknown members")
    domain = _domain(payload["domain"])
    key_id = payload["key_id"]
    if not isinstance(key_id, str) or not KEY_ID_RE.fullmatch(key_id):
        raise ValueError("authorization key_id is invalid")
    try:
        public = base64.b64decode(payload["public_key"], validate=True)
    except (TypeError, ValueError) as error:
        raise ValueError("authorization public_key is invalid Base64") from error
    if len(public) != 32 or _key_id(public) != key_id:
        raise ValueError("authorization key_id does not match public_key")
    allowed = payload["allowed_types"]
    if (
        not isinstance(allowed, list)
        or not allowed
        or any(not _valid_type(item) for item in allowed)
        or len(set(allowed)) != len(allowed)
        or allowed != sorted(allowed)
    ):
        raise ValueError("authorization allowed_types must be sorted and unique")
    start = _parse_time(payload["valid_from"], "authorization valid_from")
    end = _parse_time(payload["valid_until"], "authorization valid_until")
    if end <= start:
        raise ValueError("authorization valid_until must be after valid_from")
    return {
        **payload,
        "domain": domain,
        "public_raw": public,
        "start": start,
        "end": end,
    }


def authorize_subordinate_key(
    *,
    domain: str,
    domain_private_key: str | Path,
    subordinate_public_key: str | Path,
    allowed_types: Sequence[str],
    valid_from: str,
    valid_until: str,
    output: str | Path,
    created_at: str | None = None,
) -> dict[str, Any]:
    """Create one domain-signed, exactly scoped subordinate-key authorization."""
    origin = _domain(domain)
    allowed = sorted(allowed_types)
    if not allowed or any(not _valid_type(item) for item in allowed):
        raise ValueError("at least one valid event type is required")
    if len(set(allowed)) != len(allowed):
        raise ValueError("allowed event types must be unique")
    start = _parse_time(valid_from, "valid_from")
    end = _parse_time(valid_until, "valid_until")
    if end <= start:
        raise ValueError("valid_until must be after valid_from")
    created = created_at or datetime.now(timezone.utc).isoformat(
        timespec="seconds"
    ).replace("+00:00", "Z")
    created_time = _parse_time(created, "created_at")
    if created_time < start or created_time >= end:
        raise ValueError("authorization created_at must be inside its validity window")
    subordinate = _load_public_key(Path(subordinate_public_key))
    key_id = _key_id(subordinate)
    unsigned = {
        "govp": "GOVP-EXT-1",
        "extension": PUBLICATION_EXTENSION,
        "type": AUTHORIZATION_TYPE,
        "id": f"AUTH-{key_id.removeprefix('sha256:')[:20]}",
        "issuer": {
            "canonical": f"{origin}/.well-known/govp.txt",
            "name": urlsplit(origin).hostname,
        },
        "subject": {"type": "subordinate-key", "id": key_id},
        "created_at": created,
        "hash": {"alg": "sha256", "value": _sha(subordinate)},
        "payload": {
            "allowed_types": allowed,
            "domain": origin,
            "key_id": key_id,
            "public_key": base64.b64encode(subordinate).decode("ascii"),
            "valid_from": valid_from,
            "valid_until": valid_until,
        },
        "references": [],
        "evidence": [],
        "origin": {
            "origin": "system_observed",
            "observed_by": "govp publication authorize-key/1.0.0",
            "observation": {
                "domain": origin,
                "key_id": key_id,
                "scope_count": len(allowed),
            },
        },
    }
    envelope = sign_envelope(unsigned, _load_private_key(Path(domain_private_key)))
    if not verify_envelope(envelope, subject_bytes=subordinate).ok:
        raise ValueError("generated authorization did not verify")
    destination = Path(output)
    _write_json(destination, envelope)
    return envelope


def event_descriptor(envelope: Mapping[str, Any]) -> dict[str, str]:
    """Return the exact descriptor committed by the publication Merkle tree."""
    event_id = envelope.get("id")
    event_type = envelope.get("type")
    signature = envelope.get("signature")
    if not isinstance(event_id, str) or not event_id or len(event_id) > 256:
        raise ValueError("event id is invalid")
    if not _valid_type(event_type):
        raise ValueError("event type is invalid")
    if not isinstance(signature, Mapping):
        raise TypeError("event signature is missing")
    key_id = signature.get("key_id")
    signing_hash = signature.get("signing_input_sha256")
    if not isinstance(key_id, str) or not KEY_ID_RE.fullmatch(key_id):
        raise ValueError("event key_id is invalid")
    if not isinstance(signing_hash, str) or not SHA_RE.fullmatch(signing_hash):
        raise ValueError("event signing_input_sha256 is invalid")
    return {
        "id": event_id,
        "key_id": key_id,
        "signing_input_sha256": signing_hash,
        "type": str(event_type),
    }


def publication_entry_id(descriptor: Mapping[str, str]) -> str:
    """Derive the stable shard key from the event ID and signing bytes."""
    return _sha(
        descriptor["id"].encode("utf-8")
        + b"\x00"
        + descriptor["signing_input_sha256"].encode("ascii")
    )


def publication_leaf(descriptor: Mapping[str, str]) -> bytes:
    return hashlib.sha256(b"\x00" + canonical_json(dict(descriptor)).encode()).digest()


def _largest_power_less_than(value: int) -> int:
    power = 1
    while power * 2 < value:
        power *= 2
    return power


def _root_range(
    leaves: Sequence[bytes],
    start: int,
    end: int,
    cache: dict[tuple[int, int], bytes],
) -> bytes:
    key = (start, end)
    if key in cache:
        return cache[key]
    length = end - start
    if length == 0:
        result = EMPTY_ROOT
    elif length == 1:
        result = leaves[start]
    else:
        split = _largest_power_less_than(length)
        left = _root_range(leaves, start, start + split, cache)
        right = _root_range(leaves, start + split, end, cache)
        result = hashlib.sha256(b"\x01" + left + right).digest()
    cache[key] = result
    return result


def merkle_root(leaves: Sequence[bytes]) -> bytes:
    """Compute the RFC 6962 root used by the existing GOVP mesh."""
    return _root_range(leaves, 0, len(leaves), {})


def _audit_path(
    leaves: Sequence[bytes],
    index: int,
    cache: dict[tuple[int, int], bytes] | None = None,
) -> list[list[Any]]:
    if index < 0 or index >= len(leaves):
        raise IndexError("Merkle proof index is outside the tree")
    roots = cache if cache is not None else {}

    def walk(start: int, end: int, relative: int) -> list[list[Any]]:
        length = end - start
        if length <= 1:
            return []
        split = _largest_power_less_than(length)
        if relative < split:
            path = walk(start, start + split, relative)
            sibling = _root_range(leaves, start + split, end, roots)
            path.append([sibling.hex(), True])
            return path
        path = walk(start + split, end, relative - split)
        sibling = _root_range(leaves, start, start + split, roots)
        path.append([sibling.hex(), False])
        return path

    return walk(0, len(leaves), index)


def _fold_path(leaf: bytes, path: Any) -> bytes:
    if not isinstance(path, list) or len(path) > 64:
        raise ValueError("Merkle path is invalid")
    value = leaf
    for step in path:
        if (
            not isinstance(step, list)
            or len(step) != 2
            or not isinstance(step[0], str)
            or not SHA_RE.fullmatch(step[0])
            or not isinstance(step[1], bool)
        ):
            raise ValueError("Merkle path step is invalid")
        sibling = bytes.fromhex(step[0])
        value = (
            hashlib.sha256(b"\x01" + value + sibling).digest()
            if step[1]
            else hashlib.sha256(b"\x01" + sibling + value).digest()
        )
    return value


def build_publication_tree(
    descriptors: Sequence[Mapping[str, str]], batch_id: str
) -> tuple[str, dict[str, dict[str, Any]]]:
    """Build the mesh-compatible 256-shard root and every O(log N) proof."""
    _safe_id(batch_id, "batch_id")
    entries: list[tuple[str, dict[str, str]]] = []
    event_ids: set[str] = set()
    entry_ids: set[str] = set()
    for item in descriptors:
        descriptor = dict(item)
        # Revalidate caller-created descriptors through the public constructor.
        if set(descriptor) != {"id", "key_id", "signing_input_sha256", "type"}:
            raise ValueError("publication descriptor has missing or unknown members")
        entry_id = publication_entry_id(descriptor)
        if descriptor["id"] in event_ids or entry_id in entry_ids:
            raise ValueError("publication batch contains a duplicate event")
        event_ids.add(descriptor["id"])
        entry_ids.add(entry_id)
        entries.append((entry_id, descriptor))
    if not entries:
        raise ValueError("publication batch must contain at least one event")
    entries.sort(key=lambda item: item[0])
    buckets: list[list[tuple[str, dict[str, str]]]] = [
        [] for _ in range(SHARDS)
    ]
    for entry_id, descriptor in entries:
        buckets[int(entry_id[-2:], 16)].append((entry_id, descriptor))
    shard_roots: list[bytes] = []
    shard_leaves: list[list[bytes]] = []
    for bucket in buckets:
        leaves = [publication_leaf(descriptor) for _, descriptor in bucket]
        shard_leaves.append(leaves)
        shard_roots.append(merkle_root(leaves))
    root = merkle_root(shard_roots)
    top_cache: dict[tuple[int, int], bytes] = {}
    proofs: dict[str, dict[str, Any]] = {}
    for shard, bucket in enumerate(buckets):
        if not bucket:
            continue
        intra_cache: dict[tuple[int, int], bytes] = {}
        for index, (entry_id, descriptor) in enumerate(bucket):
            proofs[entry_id] = {
                "batch_id": batch_id,
                "descriptor": descriptor,
                "entry_id": entry_id,
                "intra_proof": _audit_path(
                    shard_leaves[shard], index, intra_cache
                ),
                "root": root.hex(),
                "shard": shard,
                "shard_root": shard_roots[shard].hex(),
                "top_proof": _audit_path(shard_roots, shard, top_cache),
            }
    return root.hex(), proofs


def verify_publication_proof(
    envelope: Mapping[str, Any], proof: Mapping[str, Any], expected_root: str
) -> bool:
    """Verify descriptor binding, shard selection and both RFC 6962 paths."""
    try:
        descriptor = event_descriptor(envelope)
        if proof.get("descriptor") != descriptor:
            return False
        entry_id = publication_entry_id(descriptor)
        if proof.get("entry_id") != entry_id:
            return False
        shard = int(entry_id[-2:], 16)
        if proof.get("shard") != shard or proof.get("root") != expected_root:
            return False
        intra = _fold_path(publication_leaf(descriptor), proof.get("intra_proof"))
        if proof.get("shard_root") != intra.hex():
            return False
        top_path = proof.get("top_proof")
        if not isinstance(top_path, list) or len(top_path) != 8:
            return False
        return _fold_path(intra, top_path).hex() == expected_root
    except (KeyError, TypeError, ValueError):
        return False


def _validate_status(status: Mapping[str, Any], domain: str) -> None:
    if not status_format_ok(status):
        raise ValueError("status snapshot is invalid")
    if status.get("canonical") != f"{domain}/.well-known/govp/revoked.json":
        raise ValueError("status snapshot is not canonical for the publication domain")


def _status_key(
    status: Mapping[str, Any], key_id: str, at: datetime
) -> Mapping[str, Any] | None:
    keys = status.get("keys")
    if not isinstance(keys, list):
        return None
    matches = [item for item in keys if item.get("key_id") == key_id]
    if len(matches) != 1:
        return None
    key = matches[0]
    changed = _parse_time(key.get("changed_at"), "status key changed_at")
    state = key.get("state")
    if state == "active" and at >= changed:
        return key
    if state == "retired" and at < changed:
        return key
    return None


def _verify_authorization(
    authorization: Mapping[str, Any], status: Mapping[str, Any], domain: str
) -> tuple[dict[str, Any], str]:
    if authorization.get("type") != AUTHORIZATION_TYPE:
        raise ValueError("authorization envelope has the wrong type")
    if authorization.get("extension") != PUBLICATION_EXTENSION:
        raise ValueError("authorization envelope has the wrong extension")
    if authorization.get("issuer", {}).get("canonical") != (
        f"{domain}/.well-known/govp.txt"
    ):
        raise ValueError("authorization issuer does not match the domain")
    payload = _authorization_payload(authorization.get("payload"))
    if payload["domain"] != domain:
        raise ValueError("authorization payload domain does not match")
    if not verify_envelope(
        authorization, subject_bytes=payload["public_raw"]
    ).ok:
        raise ValueError("authorization envelope is not L0-valid")
    created = _parse_time(authorization.get("created_at"), "authorization created_at")
    if not (payload["start"] <= created < payload["end"]):
        raise ValueError("authorization created_at is outside its validity window")
    domain_key_id = authorization.get("signature", {}).get("key_id")
    if not isinstance(domain_key_id, str) or _status_key(
        status, domain_key_id, created
    ) is None:
        raise ValueError("authorization domain key is not valid in the status snapshot")
    return payload, domain_key_id


def _batch_envelope(
    *,
    batch_id: str,
    created_at: str,
    disposition: str,
    descriptors: Sequence[Mapping[str, str]],
    root: str,
    domain: str,
    domain_key: Ed25519PrivateKey,
    workload: Mapping[str, str],
) -> dict[str, Any]:
    root_bytes = bytes.fromhex(root)
    payload = {
        "batch_id": batch_id,
        "count": len(descriptors),
        "disposition": disposition,
        "event_types": sorted({item["type"] for item in descriptors}),
        "root": root,
        "shards": SHARDS,
        "tree_alg": TREE_ALGORITHM,
    }
    unsigned = {
        "govp": "GOVP-EXT-1",
        "extension": PUBLICATION_EXTENSION,
        "type": BATCH_TYPE,
        "id": f"BATCH-{batch_id}",
        "issuer": {
            "canonical": f"{domain}/.well-known/govp.txt",
            "name": urlsplit(domain).hostname,
        },
        "subject": {"type": "publication-batch-root", "id": batch_id},
        "created_at": created_at,
        "hash": {"alg": "sha256", "value": _sha(root_bytes)},
        "payload": payload,
        "references": [],
        "evidence": [],
        "origin": {
            "origin": "system_observed",
            "observed_by": "govp publish/1.0.0",
            "observation": dict(workload),
        },
    }
    result = sign_envelope(unsigned, domain_key)
    if not verify_envelope(result, subject_bytes=root_bytes).ok:
        raise ValueError("generated publication batch did not verify")
    return result


def _github_workload(request: Mapping[str, Any]) -> dict[str, str]:
    workload = request.get("workload")
    if not isinstance(workload, dict) or set(workload) != {"refs", "repository"}:
        raise ValueError("publish request workload is invalid")
    refs = workload["refs"]
    repository = workload["repository"]
    if (
        not isinstance(refs, list)
        or not refs
        or any(not isinstance(item, str) for item in refs)
        or not isinstance(repository, str)
    ):
        raise ValueError("publish request workload is invalid")
    observed = {
        "provider": "github-actions",
        "repository": os.environ.get("GITHUB_REPOSITORY", ""),
        "ref": os.environ.get("GITHUB_REF", ""),
        "commit": os.environ.get("GITHUB_SHA", ""),
        "run_id": os.environ.get("GITHUB_RUN_ID", ""),
        "workflow_ref": os.environ.get("GITHUB_WORKFLOW_REF", ""),
    }
    if os.environ.get("GITHUB_ACTIONS") != "true":
        raise ValueError("govp publish requires a GitHub Actions workload")
    if (
        observed["repository"] != repository
        or observed["ref"] not in refs
        or not re.fullmatch(r"[0-9a-fA-F]{40}", observed["commit"])
        or not observed["run_id"].isdigit()
        or not observed["workflow_ref"]
    ):
        raise ValueError("GitHub Actions workload does not match the request")
    return observed


def _request_shape(request: Mapping[str, Any]) -> None:
    required = {
        "authorization",
        "batch_id",
        "created_at",
        "domain",
        "events",
        "identity_record",
        "publish_types",
        "schema",
        "status",
        "workload",
    }
    observed = set(request)
    if observed != required and observed != required | {"base_index"}:
        raise ValueError("publish request has missing or unknown members")
    if request.get("schema") != "org.govp.publish-request/1":
        raise ValueError("publish request schema is invalid")
    _domain(request.get("domain"))
    _safe_id(request.get("batch_id"), "batch_id")
    _parse_time(request.get("created_at"), "created_at")
    publish_types = request.get("publish_types")
    if (
        not isinstance(publish_types, list)
        or not publish_types
        or any(not _valid_type(item) for item in publish_types)
        or len(set(publish_types)) != len(publish_types)
    ):
        raise ValueError("publish_types must be an explicit unique type list")
    events = request.get("events")
    if not isinstance(events, list) or not 1 <= len(events) <= 100000:
        raise ValueError("events must contain between 1 and 100000 entries")


def _prepare_directory(destination: Path, label: str) -> tuple[Path, Path]:
    if destination.exists():
        raise ValueError(f"{label} already exists: {destination}")
    parent = destination.parent.resolve(strict=True)
    staging = Path(tempfile.mkdtemp(prefix=f".{destination.name}.", dir=parent))
    return destination, staging


def publish_request(
    *,
    request_path: str | Path,
    domain_private_key: str | Path,
    public_dir: str | Path,
    custody_dir: str | Path,
) -> PublicationOutput:
    """Validate everything, then atomically emit public and custody trees."""
    request_file = Path(request_path).resolve(strict=True)
    root = request_file.parent
    request = _load_json(request_file, "publish request")
    _request_shape(request)
    workload = _github_workload(request)
    domain = _domain(request["domain"])
    batch_id = _safe_id(request["batch_id"], "batch_id")
    created_at = request["created_at"]
    created = _parse_time(created_at, "created_at")
    domain_key = _load_private_key(Path(domain_private_key))
    domain_key_id = _key_id(_public_raw(domain_key))

    status_path = _resolve(root, request["status"], "status")
    status = parse_status(status_path.read_text(encoding="utf-8"))
    _validate_status(status, domain)
    status_entry = _status_key(status, domain_key_id, created)
    if status_entry is None or status_entry.get("state") != "active":
        raise ValueError("publication domain key is not active in the status snapshot")

    identity_path = _resolve(root, request["identity_record"], "identity_record")
    identity = load_record(identity_path)
    if (
        not verify(identity).ok
        or identity.get("canonical") != f"{domain}/.well-known/govp.txt"
    ):
        raise ValueError("identity_record is not a valid canonical domain identity")

    authorization_path = _resolve(root, request["authorization"], "authorization")
    authorization = load_envelope(authorization_path)
    authorization_payload, authorization_domain_key = _verify_authorization(
        authorization, status, domain
    )
    if authorization_domain_key != domain_key_id:
        raise ValueError("authorization and publication use different domain keys")
    if not (authorization_payload["start"] <= created < authorization_payload["end"]):
        raise ValueError("publication time is outside the authorization window")

    publish_types = set(request["publish_types"])
    public_events: list[tuple[dict[str, Any], bytes, dict[str, str]]] = []
    private_events: list[tuple[dict[str, Any], bytes, dict[str, str]]] = []
    seen_ids: set[str] = set()
    for index, item in enumerate(request["events"]):
        if not isinstance(item, dict) or set(item) != {
            "disposition",
            "envelope",
            "subject",
        }:
            raise ValueError(f"events[{index}] has missing or unknown members")
        disposition = item["disposition"]
        if disposition not in {"publish", "sealed_private"}:
            raise ValueError(f"events[{index}] disposition is invalid")
        envelope_path = _resolve(root, item["envelope"], f"events[{index}].envelope")
        subject_path = _resolve(root, item["subject"], f"events[{index}].subject")
        if subject_path.stat().st_size > MAX_SUBJECT_BYTES:
            raise ValueError(f"events[{index}] subject exceeds 64 MiB")
        envelope = load_envelope(envelope_path)
        subject = subject_path.read_bytes()
        if not verify_envelope(envelope, subject_bytes=subject).ok:
            raise ValueError(f"events[{index}] is not L0-valid")
        descriptor = event_descriptor(envelope)
        if descriptor["id"] in seen_ids:
            raise ValueError("publication request contains a duplicate event id")
        seen_ids.add(descriptor["id"])
        if descriptor["key_id"] != authorization_payload["key_id"]:
            raise ValueError(f"events[{index}] is signed by an unauthorized key")
        if envelope.get("issuer", {}).get("canonical") != (
            f"{domain}/.well-known/govp.txt"
        ):
            raise ValueError(f"events[{index}] issuer does not match the domain")
        event_time = _parse_time(envelope.get("created_at"), f"events[{index}].created_at")
        if not (
            authorization_payload["start"]
            <= event_time
            < authorization_payload["end"]
        ):
            raise ValueError(f"events[{index}] is outside the key validity window")
        if descriptor["type"] not in authorization_payload["allowed_types"]:
            raise ValueError(f"events[{index}] is outside the subordinate key scope")
        target = public_events if disposition == "publish" else private_events
        if disposition == "publish" and descriptor["type"] not in publish_types:
            raise ValueError(f"events[{index}] type was not opted in for publication")
        target.append((envelope, subject, descriptor))

    public_destination, public_stage = _prepare_directory(
        Path(public_dir), "public_dir"
    )
    custody_destination, custody_stage = _prepare_directory(
        Path(custody_dir), "custody_dir"
    )
    public_root: str | None = None
    private_root: str | None = None
    try:
        well_known = public_stage / ".well-known/govp"
        publication_root = well_known / "publication"
        well_known.mkdir(parents=True)
        shutil.copyfile(identity_path, public_stage / ".well-known/govp.txt")
        shutil.copyfile(status_path, well_known / "revoked.json")
        shutil.copyfile(authorization_path, custody_stage / "authorization.json")
        shutil.copyfile(status_path, custody_stage / "status.json")

        public_batch: dict[str, Any] | None = None
        private_batch: dict[str, Any] | None = None
        public_proofs: dict[str, dict[str, Any]] = {}
        private_proofs: dict[str, dict[str, Any]] = {}
        if public_events:
            descriptors = [item[2] for item in public_events]
            public_root, public_proofs = build_publication_tree(descriptors, batch_id)
            public_batch = _batch_envelope(
                batch_id=batch_id,
                created_at=created_at,
                disposition="publish",
                descriptors=descriptors,
                root=public_root,
                domain=domain,
                domain_key=domain_key,
                workload=workload,
            )
            _write_json(
                publication_root / "batches" / f"{batch_id}.json", public_batch
            )
            key_name = authorization_payload["key_id"].removeprefix("sha256:")
            _write_json(
                publication_root / "keys" / f"{key_name}.json", authorization
            )
        if private_events:
            private_batch_id = f"{batch_id}-sealed"
            private_descriptors = [item[2] for item in private_events]
            private_root, private_proofs = build_publication_tree(
                private_descriptors, private_batch_id
            )
            private_batch = _batch_envelope(
                batch_id=private_batch_id,
                created_at=created_at,
                disposition="sealed_private",
                descriptors=private_descriptors,
                root=private_root,
                domain=domain,
                domain_key=domain_key,
                workload=workload,
            )

        publication_index = {
            "batches": []
            if public_batch is None
            else [
                {
                    "count": len(public_events),
                    "created_at": created_at,
                    "id": batch_id,
                    "root": public_root,
                    "url": f"{domain}/.well-known/govp/publication/batches/{batch_id}.json",
                }
            ],
            "canonical": f"{domain}/.well-known/govp/publication/index.json",
            "format": "GOVP-PUBLICATION-INDEX-1",
            "identity": f"{domain}/.well-known/govp.txt",
            "publication": f"{domain}/.well-known/govp/publication/index.json",
            "status": f"{domain}/.well-known/govp/revoked.json",
        }
        _write_json(publication_root / "index.json", publication_index)
        if "base_index" in request:
            discovery = _load_json(
                _resolve(root, request["base_index"], "base_index"), "base index"
            )
        else:
            discovery = {
                "canonical": f"{domain}/.well-known/govp/index.json",
                "format": "GOVP-DISCOVERY-1",
                "identity": f"{domain}/.well-known/govp.txt",
                "status": f"{domain}/.well-known/govp/revoked.json",
            }
        discovery["publication"] = publication_index["publication"]
        _write_json(well_known / "index.json", discovery)

        for disposition, events, proofs, batch in (
            ("publish", public_events, public_proofs, public_batch),
            ("sealed_private", private_events, private_proofs, private_batch),
        ):
            if batch is None:
                continue
            _write_json(
                custody_stage / "batches" / f"{batch['payload']['batch_id']}.json",
                batch,
            )
            for envelope, subject, descriptor in events:
                entry_id = publication_entry_id(descriptor)
                _write_json(custody_stage / "records" / f"{entry_id}.json", envelope)
                subject_path = custody_stage / "subjects" / f"{entry_id}.bin"
                subject_path.parent.mkdir(parents=True, exist_ok=True)
                with subject_path.open("xb") as handle:
                    handle.write(subject)
                bundle = {
                    "authorization_key_id": authorization_payload["key_id"],
                    "batch_id": batch["payload"]["batch_id"],
                    "disposition": disposition,
                    "envelope": envelope,
                    "proof": proofs[entry_id],
                    "schema": "org.govp.publication-proof/1",
                    "subject_base64": base64.b64encode(subject).decode("ascii"),
                }
                _write_json(custody_stage / "proofs" / f"{entry_id}.json", bundle)
        _write_json(
            custody_stage / "manifest.json",
            {
                "authorization_key_id": authorization_payload["key_id"],
                "batch_id": batch_id,
                "created_at": created_at,
                "format": "GOVP-PUBLICATION-CUSTODY-1",
                "public": {"count": len(public_events), "root": public_root},
                "sealed_private": {
                    "count": len(private_events),
                    "root": private_root,
                },
            },
        )
        os.replace(custody_stage, custody_destination)
        os.replace(public_stage, public_destination)
    except Exception:
        shutil.rmtree(public_stage, ignore_errors=True)
        shutil.rmtree(custody_stage, ignore_errors=True)
        raise
    return PublicationOutput(
        public_destination,
        custody_destination,
        len(public_events),
        len(private_events),
        public_root,
        private_root,
    )


def _batch_payload(batch: Mapping[str, Any]) -> dict[str, Any]:
    payload = batch.get("payload")
    if not isinstance(payload, dict) or set(payload) != {
        "batch_id",
        "count",
        "disposition",
        "event_types",
        "root",
        "shards",
        "tree_alg",
    }:
        raise ValueError("batch payload has missing or unknown members")
    if (
        batch.get("type") != BATCH_TYPE
        or batch.get("extension") != PUBLICATION_EXTENSION
        or payload.get("tree_alg") != TREE_ALGORITHM
        or payload.get("shards") != SHARDS
        or not isinstance(payload.get("count"), int)
        or payload["count"] < 1
        or not isinstance(payload.get("root"), str)
        or not SHA_RE.fullmatch(payload["root"])
        or payload.get("disposition") not in {"publish", "sealed_private"}
    ):
        raise ValueError("batch payload is invalid")
    _safe_id(payload.get("batch_id"), "batch_id")
    return payload


def _verify_components(
    *,
    bundle: Mapping[str, Any],
    batch: Mapping[str, Any],
    authorization: Mapping[str, Any],
    status: Mapping[str, Any],
    domain: str,
    live: bool,
    now: datetime | None = None,
) -> PublicationVerification:
    reasons: list[str] = []
    event = bundle.get("envelope")
    if not isinstance(event, dict):
        return PublicationVerification(False, {"L0": False, "L1": None, "L2": None}, ("INVALID_BUNDLE",))
    event_id = event.get("id") if isinstance(event.get("id"), str) else None
    try:
        if bundle.get("schema") != "org.govp.publication-proof/1":
            raise ValueError("INVALID_BUNDLE")
        encoded = bundle.get("subject_base64")
        if not isinstance(encoded, str) or len(encoded) > (MAX_SUBJECT_BYTES * 4 // 3 + 4):
            raise ValueError("INVALID_BUNDLE")
        subject = base64.b64decode(encoded, validate=True)
        if len(subject) > MAX_SUBJECT_BYTES:
            raise ValueError("INVALID_BUNDLE")
        batch_payload = _batch_payload(batch)
        root = batch_payload["root"]
        domain = _domain(domain)
        _validate_status(status, domain)
        authorization_payload, domain_key_id = _verify_authorization(
            authorization, status, domain
        )
        if (
            batch.get("issuer", {}).get("canonical")
            != f"{domain}/.well-known/govp.txt"
            or batch.get("signature", {}).get("key_id") != domain_key_id
            or not verify_envelope(batch, subject_bytes=bytes.fromhex(root)).ok
        ):
            raise ValueError("INVALID_BATCH")
        batch_created = _parse_time(batch.get("created_at"), "batch created_at")
        if _status_key(status, domain_key_id, batch_created) is None:
            raise ValueError("INVALID_BATCH")
        if not verify_envelope(event, subject_bytes=subject).ok:
            raise ValueError("INVALID_EVENT")
    except (KeyError, TypeError, ValueError) as error:
        reason = str(error) if str(error).isupper() else "INVALID_L0"
        return PublicationVerification(
            False,
            {"L0": False, "L1": None, "L2": None},
            (reason,),
            event_id,
            bundle.get("batch_id") if isinstance(bundle.get("batch_id"), str) else None,
        )

    descriptor = event_descriptor(event)
    event_time = _parse_time(event["created_at"], "event created_at")
    if descriptor["key_id"] != authorization_payload["key_id"]:
        reasons.append("KEY_NOT_AUTHORIZED")
    if event.get("issuer", {}).get("canonical") != f"{domain}/.well-known/govp.txt":
        reasons.append("DOMAIN_MISMATCH")
    if descriptor["type"] not in authorization_payload["allowed_types"]:
        reasons.append("SCOPE_MISMATCH")
    if not (authorization_payload["start"] <= event_time < authorization_payload["end"]):
        reasons.append("AUTHORIZATION_WINDOW_MISMATCH")
    if bundle.get("authorization_key_id") != authorization_payload["key_id"]:
        reasons.append("KEY_NOT_AUTHORIZED")
    if bundle.get("batch_id") != batch_payload["batch_id"]:
        reasons.append("BATCH_MISMATCH")
    if bundle.get("disposition") != batch_payload["disposition"]:
        reasons.append("DISPOSITION_MISMATCH")
    proof = bundle.get("proof")
    if not isinstance(proof, dict) or not verify_publication_proof(event, proof, root):
        reasons.append("INCLUSION_INVALID")
    if descriptor["type"] not in batch_payload.get("event_types", []):
        reasons.append("BATCH_MISMATCH")
    if reasons:
        return PublicationVerification(
            False,
            {"L0": True, "L1": False, "L2": None},
            tuple(dict.fromkeys(reasons)),
            event_id,
            batch_payload["batch_id"],
        )

    l2: bool | None = None
    if live:
        clock = now or datetime.now(timezone.utc)
        generated = _parse_time(status.get("generated_at"), "status generated_at")
        age = (clock - generated).total_seconds()
        l2 = -60 <= age <= 300 and _status_key(status, domain_key_id, clock) is not None
        if not l2:
            reasons.append("CURRENT_STATUS_INVALID")
    return PublicationVerification(
        not reasons,
        {"L0": True, "L1": True, "L2": l2},
        tuple(reasons),
        event_id,
        batch_payload["batch_id"],
    )


def verify_publication_tree(
    bundle_path: str | Path, tree: str | Path
) -> PublicationVerification:
    """Verify a proof using only files from a static output tree."""
    bundle = _load_json(Path(bundle_path).resolve(strict=True), "inclusion bundle")
    root = Path(tree).resolve(strict=True)
    well_known = root / ".well-known/govp"
    batch_id = _safe_id(bundle.get("batch_id"), "batch_id")
    key_id = bundle.get("authorization_key_id")
    if not isinstance(key_id, str) or not KEY_ID_RE.fullmatch(key_id):
        raise ValueError("authorization_key_id is invalid")
    batch = _load_json(
        well_known / "publication/batches" / f"{batch_id}.json", "batch"
    )
    authorization = _load_json(
        well_known
        / "publication/keys"
        / f"{key_id.removeprefix('sha256:')}.json",
        "authorization",
    )
    status = parse_status((well_known / "revoked.json").read_text(encoding="utf-8"))
    domain = str(authorization.get("payload", {}).get("domain", ""))
    return _verify_components(
        bundle=bundle,
        batch=batch,
        authorization=authorization,
        status=status,
        domain=domain,
        live=False,
    )


def verify_publication_custody(
    bundle_path: str | Path, custody: str | Path
) -> PublicationVerification:
    """Verify a public or sealed-private bundle from retained local custody."""
    bundle = _load_json(Path(bundle_path).resolve(strict=True), "inclusion bundle")
    root = Path(custody).resolve(strict=True)
    batch_id = _safe_id(bundle.get("batch_id"), "batch_id")
    batch = _load_json(root / "batches" / f"{batch_id}.json", "batch")
    authorization = _load_json(root / "authorization.json", "authorization")
    status = parse_status((root / "status.json").read_text(encoding="utf-8"))
    domain = str(authorization.get("payload", {}).get("domain", ""))
    return _verify_components(
        bundle=bundle,
        batch=batch,
        authorization=authorization,
        status=status,
        domain=domain,
        live=False,
    )


class _NoRedirects(HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):
        return None


def _static_base(value: str) -> tuple[str, bool]:
    parsed = urlsplit(value)
    loopback = parsed.scheme == "http" and parsed.hostname in {"127.0.0.1", "::1", "localhost"}
    if (
        (parsed.scheme != "https" and not loopback)
        or not parsed.hostname
        or parsed.username is not None
        or parsed.password is not None
        or parsed.path not in {"", "/"}
        or parsed.query
        or parsed.fragment
    ):
        raise ValueError("base URL must be HTTPS or explicit loopback HTTP")
    return f"{parsed.scheme}://{parsed.netloc}", not loopback


def _fetch_static(base: str, relative: str) -> bytes:
    url = base + relative
    handlers: list[Any] = [_NoRedirects()]
    if base.startswith("https://"):
        handlers.append(HTTPSHandler(context=ssl.create_default_context(cafile=certifi.where())))
    opener = build_opener(*handlers)
    request = Request(url, headers={"Accept": "application/json", "User-Agent": "govp-publication/1.0.0"})
    with opener.open(request, timeout=15) as response:  # nosec B310 -- bounded validated URL
        if response.geturl() != url:
            raise ValueError("static publication redirect is not allowed")
        declared = int(response.headers.get("content-length", "0") or "0")
        if declared > MAX_JSON_BYTES:
            raise ValueError("static publication file is too large")
        raw = response.read(MAX_JSON_BYTES + 1)
    if len(raw) > MAX_JSON_BYTES:
        raise ValueError("static publication file is too large")
    return raw


def verify_publication_url(
    bundle_path: str | Path,
    base_url: str,
    *,
    now: datetime | None = None,
) -> PublicationVerification:
    """Fetch only static files and verify a publication bundle client-side."""
    base, live = _static_base(base_url)
    bundle = _load_json(Path(bundle_path).resolve(strict=True), "inclusion bundle")
    batch_id = _safe_id(bundle.get("batch_id"), "batch_id")
    key_id = bundle.get("authorization_key_id")
    if not isinstance(key_id, str) or not KEY_ID_RE.fullmatch(key_id):
        raise ValueError("authorization_key_id is invalid")
    index = _parse_json_bytes(
        _fetch_static(base, "/.well-known/govp/publication/index.json"),
        "publication index",
    )
    domain = _domain(str(index.get("canonical", "")).removesuffix("/.well-known/govp/publication/index.json"))
    batch = _parse_json_bytes(
        _fetch_static(base, f"/.well-known/govp/publication/batches/{batch_id}.json"),
        "batch",
    )
    authorization = _parse_json_bytes(
        _fetch_static(base, f"/.well-known/govp/publication/keys/{key_id.removeprefix('sha256:')}.json"),
        "authorization",
    )
    status = parse_status(
        _fetch_static(base, "/.well-known/govp/revoked.json").decode("utf-8", errors="strict")
    )
    # Loopback is a byte mirror, never live authority. HTTPS must be same-origin.
    if live and base != domain:
        raise ValueError("HTTPS publication base does not match the signed domain")
    return _verify_components(
        bundle=bundle,
        batch=batch,
        authorization=authorization,
        status=status,
        domain=domain,
        live=live,
        now=now,
    )
